# Generated by Django 4.0.4 on 2022-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(upload_to='static/images', verbose_name='Фото'),
        ),
    ]
